### ISSUE TITLE
Information genauers hinsehen beim Routerkauf

### ISSUE THREAD

**Issue by codedust** [freifunk-darmstadt/darmstadt.freifunk.net#15]
Es sollte darauf hingewiesen werden, dass man beim Routerkauf auf die Hardwareversion achtet.

Dieses BIld wäre dafür nutzbar:

![img_20151105_215509](https://cloud.githubusercontent.com/assets/7175914/10981539/a09bf960-8408-11e5-8af1-b6f77e18fed6.jpg)

**Comment by Prednax** [comment]
Bild je empfohlenen Router ergänzen.
Formulierungsvorschlag:
Beim Kauf im Laden könnt Ihr auf der Verpackung bereits erkennen, welche Version zum Verkauf steht. Wir empfehlen entsprechend der Abbildung zu prüfen, ob die richtige Version verkauft wird.
Beim Onlinekauf habt Ihr leider nur die Möglichkeit "blind" zu kaufen. Als Privatperson ist dann ggf. ein Widerruf notwendig, falls Euch nicht die gewünschte Version geliefert wurde.

Eventuell ist es hier auch noch Hilfreich eine FAQ für die Geräteseite zu implementieren.
 - Worin liegt der Unterschied zwischen V1 und V2?
      ->Weiß ich leider auch noch nicht
 - Worin liegt der Unterschied zwischen der N Version und der ND Version der Router.
      -> Es kann die gleiche Firmware genutzt werden. Während bei der N Version die Antenne fest montiert ist, kann sie bei der ND Version ausgetauscht werden.

**Comment by flokli** [comment]
Ich denke, es sprengt den Rahmen, jede Modellrevision auf der Website einzeln zu beschreiben, sich das auch öfters ändern kann. Diese Informationen kann man sich dann auch schnell bei Interesse selbst heraussuchen.

Ich denke, ein Satz am Ende des ersten Blocks von `mitmachen/unterstuetzte-geraete/`, dass man beim Kauf auf die genaue Hardwarerevision achten soll, dürfte ausreichen.

@Miterion: magst du was formulieren?

**Comment by Prednax** [comment]
Wie wäre es mit dieser allgemeinen Formulierung:
Beim Kauf im Laden könnt Ihr auf der Verpackung bereits erkennen, welche Version zum Verkauf steht. Wir empfehlen zu prüfen, ob die richtige Version verkauft wird.
Beim Onlinekauf habt Ihr leider nur die Möglichkeit "blind" zu kaufen. Als Privatperson ist dann ggf. ein Widerruf notwendig, falls Euch nicht die gewünschte Version geliefert wurde.

**Comment by Miterion** [comment]
Ich würde das vielleicht eher anders formulieren: Achtet beim Kauf auf die Hardwarerevsision. Nicht immer existiert für ein Gerät eine Firmware, obwohl es zur selben Modellreihe gehört. Schaut daher auf die Verpackung (eventuell link aufs Bild inklusive Markierung, damit man weiß wonach man suchen muss) oder kontaktiert euren Onlineshop.

**Comment by Prednax** [comment]
Der Text  (eventuell link aufs Bild inklusive Markierung, damit man weiß wonach man suchen muss) war nur ein Hinweis für eine mögliche Einbindung des Bildes. Das fehlt auf der Homepage -> Daher sollte der Text noch raus.
