### ISSUE TITLE
Firmwaredownloadseite 

### ISSUE THREAD

**Issue by Prednax** [freifunk-darmstadt/darmstadt.freifunk.net#16]
Lässt sich auf https://firmware.darmstadt.freifunk.net der Preis automatisiert aus idealo oder ählichen Seiten abrufen und in die Tabelle einfügen?

Auf der Seite sollten die von Freifunk Darmstadt Firmwaredownload empfohlene Geräte fett hervorgehoben werden

**Comment by mweinelt** [comment]
Hallo,

das hängt davon ab, ob diese Seiten eine API bereitstellen, die das Abfragen der Preise ermöglicht. Insgesamt wollen wir aber nur wenige Geräte, die wir derzeit unterstützen, zum Neukauf empfehlen. Daher macht das vermutlich auf der Firmwareseite wenig Sinn.

Gruß Martin

**Comment by Prednax** [comment]
Dann nur den Teil des hervorhebens unserer empfohlenen Geräte.

**Comment by Miterion** [comment]
Sollte hier nochmal angefragt werden: https://github.com/freifunk-darmstadt/ffda-firmware-splash

**Comment by Prednax** [comment]
wie kommt es dorthin?

**Comment by flokli** [comment]
moved to freifunk-darmstadt/ffda-firmware-splash#1
