### ISSUE TITLE
Mouse Over für die Symbole auf der Homepage verbessern (Facebook, github ...)

### ISSUE THREAD

**Issue by Prednax** [freifunk-darmstadt/darmstadt.freifunk.net#18]
Die aktuellen Mouseover sind in der Ecke links unten versteckt und nicht dort wo sich die Maus gerade befindet. Das da überhaupt ein Mousover existiert ist mir erst heute aufgefallen.
 -> Anzeige des Mousover beim Mauszeiger implementieren
 -> Statt dem reinen Link eine Erläuterung angeben, welche Funktion sich hier verbirgt. (Freifunk bei Facebook besuchen [nicht gleich einen Like verursachen], Github - Ticketsystem für die Homepage ....)

**Comment by Miterion** [comment]
Der momentane Mouseover wird standardmäßig vom Browser generiert und funktioniert bei jedem Link internetweit. Der Klick auf den Facebook-Link verursacht kein Like, der Github-Link führt zur allgemeinen Github Seite von Freifunk Darmstadt, das würde ich mal so lassen

**Comment by Prednax** [comment]
Da es Leute gibt, denen sich die Bedeutung nicht intuitiv erschließt bin ich hier weiterhin für die Optimierung der Usability. 
Vielleicht hat jemand noch eine andere Idee?
Könnte mir vorstellen statt dessen eine Textzeile zusätzlich unter den Symbolen zu ergänzen..

**Comment by Miterion** [comment]
![image](http://www.basicwp.com/img/2012/09/wordpress-tooltip-popup-box.png)
Etwa so?

**Comment by Prednax** [comment]
wesentlich ist dass Symbole allein nicht allen verständlich sind. Wie das dann genau aussieht kann ich mir noch nicht vorstellen.

**Comment by flokli** [comment]
@Prednax: Die von dir angesprochenen Tooltips nicht standardmäßig bei allen Hyperlinks angezeigt, die im Bereich unten links angezeigte Adresse des Hyperlinks jedoch schon.

Du hast aber Recht, die Logos unten im Footer könnten etwas verwirrend sein. Ich habe für diese jetzt die angesprochenen Tooltips eingefügt.
