### ISSUE TITLE
Update Termine auf der Homepage

### ISSUE THREAD

**Issue by Prednax** [freifunk-darmstadt/darmstadt.freifunk.net#29]
Auf der Seite https://darmstadt.freifunk.net/kontakt/ wird noch von wöchentlichen Meetings gesprochen.
Hatte mitbekommen, dass dies nur noch alle 2 Wochen statt findet. Sollte sich auch auf der Homepage wiederspiegeln, damit Leute nicht umsonst kommen.

**Comment by codedust** [comment]
Unser Plenum wird in Zukunft nur noch alle 2 Wochen stattfinden. Trotzdem *treffen* wir uns weiterhin jede Woche. Besucher sind also natürlich jede Woche gerne gesehen. ;)

**Comment by Miterion** [comment]
Ich würde das aber eventuell kenntlich machen, etwa: 
>Immer am 1. und 3. Montag jedes Monats um 19:30 Uhr findet unser Plenum statt, in dem wir aktuelle Entwicklungen diskutieren und unser weiteres Vorgehen koordinieren.

**Comment by codedust** [comment]
:+1:
