### ISSUE TITLE
Anleitung, wie man sich mit darmstadt.freifunk.net als Client verbindet

### ISSUE THREAD

**Issue by codedust** [freifunk-darmstadt/darmstadt.freifunk.net#56]
Kam als Feedback auf FM

**Comment by Miterion** [comment]
Eine Anleitung wie man sich mit einem Wlan verbindet?

**Comment by codedust** [comment]
Genau! Ist zwar total trivial, aber das zeigt ja dann auch, wie leicht es ist, Freifunk zu benutzen.

**Comment by flokli** [comment]
Pull requests welcome - as always ;-)
