### ISSUE TITLE
180sec Video

### ISSUE THREAD

**Issue by codedust** [freifunk-darmstadt/darmstadt.freifunk.net#59]
Video irgendwo einbinden:
https://darmstadt.freifunk.net/media/180secFreifunkHD.mp4

Genehmigung irgendwo erwähnen! (siehe Mail)

**Comment by Miterion** [comment]
404 not found

**Comment by mweinelt** [comment]
https://media.darmstadt.freifunk.net/150secfreifunkHD.mp4
