### ISSUE TITLE
Formulierung bei "gemeinschaftlich betrieben" (4 Freifunk-Prinzipien)

### ISSUE THREAD

**Issue by codedust** [freifunk-darmstadt/darmstadt.freifunk.net#64]
> Mit einem eigenen Accesspoint kannst du das Netz erweitern und stabilisieren, sowie einen Internet-Hotspot für alle bereitstellen.

besser:
> Mit einem eigenen Accesspoint kannst du das Netz erweitern und stabilisieren, sowie deinen Gästen und Nachbarn einen freien Internetzugang bieten.

"bieten" finde ich noch nicht perfekt. Hat da jemand eine Idee?

**Comment by azrdev** [comment]
bieten - bereitstellen?
auch: vllt statt "Internet" lieber "Netz"?

**Comment by blocktrron** [comment]
"Gästen und Nachbarn" impiziert mmn. das heraussuchen der Nutzergruppe.

> Mit einem eigenen Accesspoint kannst du das Netz erweitern und stabilisieren, sowie einen freien Netzzugang für alle bereitstellen.

In dem Kontext, dass der Knotenbetreiber anderen den Zugang öffnet finde ich auch "bieten" oder "bereitstellen" nicht verkehrt.
