### ISSUE TITLE
Party in Oetinger Villa: wann?

### ISSUE THREAD

**Issue by okin** [freifunk-darmstadt/darmstadt.freifunk.net#7]
Bei dem aktuellen News-Post frage ich mich noch wann das ganze ist - also nicht das Datum, sondern wieviel Uhr. ;)

**Comment by flokli** [comment]
fixed in d7bd189e6e496fb254b521b507739cb329b30e21.

see: http://darmstadt.freifunk.net/news/2015/03/16/wir-feiern-den-100sten-hotspot/
